# File: _config.yml
webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"


source:      _source
destination: _deploy
theme: jekyll-theme-midnight


# Site settings
name: Liuaj's blog
email: aijia930515@126.com
author: Liuaj
url: https://laijia.github.io/
resume_site: https://laijia.github.io/
github: https://github.com/Laijia/laijia.github.io
baseurl: "/"
description: ？!
meta_description: 刘爱佳;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Laijia

# Build settings
markdown: kramdown

baidu_analysis: 7501fa07838ede8c526fafa847ec5665